#!/usr/bin/env bash
# Build a styled, vertical "drag to Applications" DMG for a channel.
#
# Usage: ./scripts/make-dmg.sh <stable|beta|nightly> <version>
#        (expects Contained.app already built in the repo root — see scripts/bundle.sh)
#
# Layout is written deterministically by `dmgbuild` (no Finder/AppleScript), so the result is
# pixel-identical every run, headless, on CI or locally.
#
# Asset fallbacks (drop your own in to override; nothing required to get a good-looking DMG):
#   Resources/dmg/background-<channel>.png  → else auto-generated by scripts/dmg-background.swift
#   Resources/dmg/volume-<channel>.icns     → else Resources/Contained.icns (the main icon) → else none
set -euo pipefail
cd "$(dirname "$0")/.."

CHANNEL="${1:?Pass the channel: stable | beta | nightly}"
VERSION="${2:?Pass the marketing version, e.g. 1.0.0 or 1.0.0-beta.4}"
APP="Contained.app"
[ -d "$APP" ] || { echo "✗ $APP not found — run scripts/bundle.sh first"; exit 1; }

case "$CHANNEL" in
  stable)  VOLNAME="Contained";          PILL="$VERSION" ;;
  beta)    VOLNAME="Contained Beta";     PILL="beta $VERSION" ;;
  nightly) VOLNAME="Contained Nightly";  PILL="nightly $VERSION" ;;
  *) echo "✗ Unknown channel '$CHANNEL' (use stable|beta|nightly)"; exit 1 ;;
esac
PILL="${3:-$PILL}"   # optional tidy pill label (workflows pass "beta 1.0.0 · 1292" etc.)

mkdir -p updates
OUT="updates/Contained-${VERSION}.dmg"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

# Background: committed override, else auto-generated.
BG="Resources/dmg/background-${CHANNEL}.png"
if [ ! -f "$BG" ]; then
  BG="$WORK/background.png"
  echo "▸ Rendering DMG background ($CHANNEL)…"
  swift scripts/dmg-background.swift "$BG" "$CHANNEL" "$PILL"
fi

# Volume icon: channel override → main app icon → none.
VOLICON=""
for cand in "Resources/dmg/volume-${CHANNEL}.icns" "Resources/Contained.icns"; do
  [ -f "$cand" ] && { VOLICON="$cand"; break; }
done

# Ensure dmgbuild is importable (CI runners + local; try the least-invasive install first).
ensure_dmgbuild() {
  python3 -c 'import dmgbuild' 2>/dev/null && return 0
  echo "▸ Installing dmgbuild…"
  pip3 install --quiet dmgbuild 2>/dev/null && return 0
  python3 -m pip install --quiet --user dmgbuild 2>/dev/null && return 0
  python3 -m pip install --quiet --user --break-system-packages dmgbuild
}
ensure_dmgbuild

APP_ABS="$(cd "$(dirname "$APP")" && pwd)/$(basename "$APP")"
BG_ABS="$(cd "$(dirname "$BG")" && pwd)/$(basename "$BG")"
if [ -n "$VOLICON" ]; then
  VOLICON_ABS="$(cd "$(dirname "$VOLICON")" && pwd)/$(basename "$VOLICON")"
  BADGE_PY="\"$VOLICON_ABS\""
else
  BADGE_PY="None"
fi

SETTINGS="$WORK/settings.py"
cat > "$SETTINGS" <<PY
import os.path
app = "$APP_ABS"
appname = os.path.basename(app)
files = [app]
symlinks = {"Applications": "/Applications"}
badge_icon = $BADGE_PY
background = "$BG_ABS"
icon_size = 104
text_size = 13
format = "UDZO"
window_rect = ((200, 200), (380, 560))
default_view = "icon-view"
icon_locations = {appname: (190, 180), "Applications": (190, 430)}
PY

echo "▸ Building $OUT (volume: $VOLNAME)…"
rm -f "$OUT"
python3 - "$OUT" "$VOLNAME" "$SETTINGS" <<'PY'
import sys, dmgbuild
dmgbuild.build_dmg(sys.argv[1], sys.argv[2], settings_file=sys.argv[3])
PY

echo "✓ $OUT"
