#!/usr/bin/env bash
# Build a styled, vertical "drag to Applications" DMG for a channel.
#
# Usage: ./scripts/make-dmg.sh <stable|beta|nightly> <version> [pill-text]
#        (expects Contained.app already built in the repo root — see scripts/bundle.sh)
#
# Uses `create-dmg`, which styles the window through Finder itself — the one method modern macOS
# reliably renders the background with (dmgbuild stores the background as an alias that Finder 26 no
# longer resolves, so the image never shows).
#
# Asset fallbacks (drop your own in to override; nothing required to get a good-looking DMG):
#   Resources/dmg/background-<channel>.png  → else auto-generated by scripts/dmg-background.swift
#   Resources/dmg/volume-<channel>.icns     → else Resources/Contained.icns (the main icon) → else none
set -euo pipefail
cd "$(dirname "$0")/.."

CHANNEL="${1:?Pass the channel: stable | beta | nightly}"
VERSION="${2:?Pass the marketing version, e.g. 1.0.0 or 1.0.0-beta.4}"
APP="Contained.app"
[ -d "$APP" ] || { echo "✗ $APP not found — run scripts/bundle.sh first"; exit 1; }

case "$CHANNEL" in
  stable)  VOLNAME="Contained";          PILL="$VERSION" ;;
  beta)    VOLNAME="Contained Beta";     PILL="beta $VERSION" ;;
  nightly) VOLNAME="Contained Nightly";  PILL="nightly $VERSION" ;;
  *) echo "✗ Unknown channel '$CHANNEL' (use stable|beta|nightly)"; exit 1 ;;
esac
PILL="${3:-$PILL}"   # optional tidy pill label (workflows pass "beta 1.0.0 · 1292" etc.)

mkdir -p updates
OUT="updates/Contained-${VERSION}.dmg"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

# Background: committed override (.tiff preferred for retina, else .png), else auto-generated as a
# HiDPI TIFF (1× + 2× folded together) so it's crisp on Retina yet positioned by its 380×560 logical
# size.
BG=""
for cand in "Resources/dmg/background-${CHANNEL}.tiff" "Resources/dmg/background-${CHANNEL}.png"; do
  [ -f "$cand" ] && { BG="$cand"; break; }
done
if [ -z "$BG" ]; then
  echo "▸ Rendering DMG background ($CHANNEL, 1× + 2× → HiDPI)…"
  swift scripts/dmg-background.swift "$WORK/bg.png"    "$CHANNEL" "$PILL" 1
  swift scripts/dmg-background.swift "$WORK/bg@2x.png" "$CHANNEL" "$PILL" 2
  BG="$WORK/background.tiff"
  tiffutil -cathidpicheck "$WORK/bg.png" "$WORK/bg@2x.png" -out "$BG" >/dev/null
fi

# Volume icon: channel override → main app icon → none.
VOLICON=""
for cand in "Resources/dmg/volume-${CHANNEL}.icns" "Resources/Contained.icns"; do
  [ -f "$cand" ] && { VOLICON="$cand"; break; }
done

command -v create-dmg >/dev/null 2>&1 || { echo "▸ Installing create-dmg…"; brew install create-dmg; }

VOLICON_ARGS=()
[ -n "$VOLICON" ] && VOLICON_ARGS=(--volicon "$VOLICON")

echo "▸ Building $OUT (volume: $VOLNAME)…"
rm -f "$OUT"
create-dmg \
  --volname "$VOLNAME" \
  "${VOLICON_ARGS[@]}" \
  --background "$BG" \
  --window-pos 200 120 \
  --window-size 380 560 \
  --icon-size 104 \
  --icon "$APP" 190 180 \
  --app-drop-link 190 430 \
  --hide-extension "$APP" \
  --no-internet-enable \
  "$OUT" "$APP"

echo "✓ $OUT"
