#!/usr/bin/env bash
# Build a styled, vertical "drag to Applications" DMG for a channel.
#
# Usage: ./scripts/make-dmg.sh <stable|beta|nightly> <version> [pill-text]
#        (expects Contained.app already built in the repo root — see scripts/bundle.sh)
#
# Uses `create-dmg`, which styles the window through Finder itself — the one method modern macOS
# reliably renders the background with (dmgbuild stores the background as an alias that Finder 26 no
# longer resolves, so the image never shows).
#
# Asset fallbacks (drop your own in to override; nothing required to get a good-looking DMG):
#   Resources/dmg/background-<channel>.png  → else auto-generated by scripts/dmg-background.swift
#   Resources/dmg/volume-<channel>.icns     → else Resources/Contained.icns (the main icon) → else none
set -euo pipefail
cd "$(dirname "$0")/.."

CHANNEL="${1:?Pass the channel: stable | beta | nightly}"
VERSION="${2:?Pass the marketing version, e.g. 1.0.0 or 1.0.0-beta.4}"
APP="Contained.app"
[ -d "$APP" ] || { echo "✗ $APP not found — run scripts/bundle.sh first"; exit 1; }

case "$CHANNEL" in
  stable)  VOLNAME="Contained";          PILL="$VERSION" ;;
  beta)    VOLNAME="Contained Beta";     PILL="beta $VERSION" ;;
  nightly) VOLNAME="Contained Nightly";  PILL="nightly $VERSION" ;;
  *) echo "✗ Unknown channel '$CHANNEL' (use stable|beta|nightly)"; exit 1 ;;
esac
PILL="${3:-$PILL}"   # optional tidy pill label (workflows pass "beta 1.0.0 · 1292" etc.)

mkdir -p updates
OUT="updates/Contained-${VERSION}.dmg"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT

# Background: committed override, else auto-generated (760×1120 = 380×560 window @2× for retina).
BG="Resources/dmg/background-${CHANNEL}.png"
if [ ! -f "$BG" ]; then
  BG="$WORK/background.png"
  echo "▸ Rendering DMG background ($CHANNEL)…"
  swift scripts/dmg-background.swift "$BG" "$CHANNEL" "$PILL"
fi

# Volume icon: channel override → main app icon → none.
VOLICON=""
for cand in "Resources/dmg/volume-${CHANNEL}.icns" "Resources/Contained.icns"; do
  [ -f "$cand" ] && { VOLICON="$cand"; break; }
done

command -v create-dmg >/dev/null 2>&1 || { echo "▸ Installing create-dmg…"; brew install create-dmg; }

VOLICON_ARGS=()
[ -n "$VOLICON" ] && VOLICON_ARGS=(--volicon "$VOLICON")

echo "▸ Building $OUT (volume: $VOLNAME)…"
rm -f "$OUT"
create-dmg \
  --volname "$VOLNAME" \
  "${VOLICON_ARGS[@]}" \
  --background "$BG" \
  --window-pos 200 120 \
  --window-size 380 560 \
  --icon-size 104 \
  --icon "$APP" 190 180 \
  --app-drop-link 190 430 \
  --hide-extension "$APP" \
  --no-internet-enable \
  "$OUT" "$APP"

echo "✓ $OUT"
