import Foundation
import SwiftData
import ContainedCore

/// Owns the SwiftData stack for the persistent history (events + metric samples) and writes to it.
/// Retention-bounded so the database can't grow without limit. The `container` is exposed so the
/// SwiftUI views can read it via `@Query`.
@MainActor
final class HistoryStore {
    let container: ModelContainer
    private var context: ModelContext { container.mainContext }

    /// Keep this many days of history; pruned on launch and periodically. Driven by the user
    /// setting (`SettingsStore.historyRetentionDays`), synced by `AppModel`.
    var retentionDays = 7
    private var lastMetricSample: Date?
    private var recentEvents: [String: Date] = [:]
    /// Minimum spacing between persisted metric samples, so a 2s poll doesn't flood the DB
    /// (60s → ~10k rows per container over the 7-day window).
    private let metricInterval: TimeInterval = 60
    /// Suppress identical durable Activity rows generated by repeated background ticks.
    private let duplicateEventWindow: TimeInterval = 30

    init() {
        let schema = Schema(HistorySchemaV1.models)
        do {
            container = try ModelContainer(for: schema,
                                           migrationPlan: HistoryMigrationPlan.self)
        } catch {
            // Fall back to an in-memory store so the app still runs if the on-disk store can't open.
            let config = ModelConfiguration(isStoredInMemoryOnly: true)
            container = try! ModelContainer(for: schema,
                                            migrationPlan: HistoryMigrationPlan.self,
                                            configurations: config)
        }
        pruneOld()
    }

    // MARK: Writes

    func record(_ kind: EventKind, containerID: String? = nil, message: String, at date: Date = Date()) {
        let key = [kind.rawValue, containerID ?? "", message].joined(separator: "\u{1F}")
        if let last = recentEvents[key], date.timeIntervalSince(last) < duplicateEventWindow { return }
        recentEvents[key] = date
        recentEvents = recentEvents.filter { date.timeIntervalSince($0.value) < duplicateEventWindow }
        context.insert(EventRecord(timestamp: date, containerID: containerID, kind: kind, message: message))
        try? context.save()
    }

    /// Persist a metric sample for each running container, throttled to `metricInterval`.
    func recordMetrics(_ deltas: [String: StatsDelta], at date: Date = Date()) {
        if let last = lastMetricSample, date.timeIntervalSince(last) < metricInterval { return }
        lastMetricSample = date
        for (id, d) in deltas {
            context.insert(MetricSample(timestamp: date, containerID: id,
                                        cpuFraction: d.cpuCoreFraction, memoryBytes: Double(d.memoryUsageBytes),
                                        netRxBytesPerSec: d.netRxBytesPerSec, netTxBytesPerSec: d.netTxBytesPerSec,
                                        diskReadBytesPerSec: d.blockReadBytesPerSec, diskWriteBytesPerSec: d.blockWriteBytesPerSec))
        }
        try? context.save()
    }

    /// Mark every recorded event as read (clears the toolbar unread badge).
    func markAllEventsRead() {
        let unread = (try? context.fetch(FetchDescriptor<EventRecord>(
            predicate: #Predicate { !$0.isRead }))) ?? []
        guard !unread.isEmpty else { return }
        for event in unread { event.isRead = true }
        try? context.save()
    }

    /// Delete every recorded event (keeps metric samples + templates). Backs the Activity "Clear" action.
    func clearEvents() {
        try? context.delete(model: EventRecord.self)
        try? context.save()
    }

    // MARK: Retention

    func pruneOld(now: Date = Date()) {
        guard let cutoff = Calendar.current.date(byAdding: .day, value: -retentionDays, to: now) else { return }
        try? context.delete(model: MetricSample.self, where: #Predicate { $0.timestamp < cutoff })
        try? context.delete(model: EventRecord.self, where: #Predicate { $0.timestamp < cutoff })
        try? context.save()
    }

    /// Wipe all recorded metrics and events (Templates are preserved). Used by the "Clear history"
    /// action in Settings.
    func clearAll() {
        try? context.delete(model: MetricSample.self)
        try? context.delete(model: EventRecord.self)
        try? context.save()
    }

    func unreadEventCount() -> Int {
        (try? context.fetchCount(FetchDescriptor<EventRecord>(
            predicate: #Predicate { !$0.isRead }))) ?? 0
    }

    func templatesSnapshot() -> [TemplateSnapshot] {
        ((try? context.fetch(FetchDescriptor<Template>())) ?? []).compactMap(TemplateSnapshot.init)
    }

    func historySnapshot() -> HistoryBackup {
        let events = ((try? context.fetch(FetchDescriptor<EventRecord>())) ?? []).map(EventRecordSnapshot.init)
        let metrics = ((try? context.fetch(FetchDescriptor<MetricSample>())) ?? []).map(MetricSampleSnapshot.init)
        return HistoryBackup(events: events, metrics: metrics)
    }

    func applyTemplates(_ snapshots: [TemplateSnapshot], replace: Bool) {
        if replace {
            try? context.delete(model: Template.self)
        }
        for snapshot in snapshots {
            context.insert(Template(snapshot: snapshot))
        }
        try? context.save()
    }

    func applyHistory(_ snapshot: HistoryBackup, replace: Bool) {
        if replace {
            try? context.delete(model: EventRecord.self)
            try? context.delete(model: MetricSample.self)
        }
        for event in snapshot.events { context.insert(EventRecord(snapshot: event)) }
        for metric in snapshot.metrics { context.insert(MetricSample(snapshot: metric)) }
        try? context.save()
    }

    func purgeOrphans(liveContainerIDs: Set<String>) -> (events: Int, metrics: Int) {
        let events = ((try? context.fetch(FetchDescriptor<EventRecord>())) ?? [])
            .filter { $0.containerID.map { !liveContainerIDs.contains($0) } ?? false }
        let metrics = ((try? context.fetch(FetchDescriptor<MetricSample>())) ?? [])
            .filter { !liveContainerIDs.contains($0.containerID) }
        for event in events { context.delete(event) }
        for metric in metrics { context.delete(metric) }
        try? context.save()
        return (events.count, metrics.count)
    }
}

struct HistoryBackup: Codable, Equatable {
    var events: [EventRecordSnapshot]
    var metrics: [MetricSampleSnapshot]
}

enum HistorySchemaV1: VersionedSchema {
    static var versionIdentifier: Schema.Version { Schema.Version(1, 0, 0) }
    static var models: [any PersistentModel.Type] {
        [EventRecord.self, MetricSample.self, Template.self]
    }
}

enum HistoryMigrationPlan: SchemaMigrationPlan {
    static var schemas: [any VersionedSchema.Type] { [HistorySchemaV1.self] }
    static var stages: [MigrationStage] { [] }
}
