import Foundation
import SwiftData
import ContainedCore
import Observation

/// Writes persistent history (events + metric samples) into the shared app database and publishes
/// bounded value projections for SwiftUI. Retention prevents unbounded database growth.
@MainActor
@Observable
final class HistoryStore {
    private static let recentActivityLimit = 300

    let container: ModelContainer
    private let database: AppDatabase
    private let reader: HistoryReader
    private var context: ModelContext { container.mainContext }

    private(set) var activitySummary = ActivitySummary()
    private(set) var recentActivity: [ActivityEvent] = []
    private(set) var activityRevision = 0
    @ObservationIgnored private var recentActivityLoaded = false

    /// Keep this many days of history; pruned on launch and periodically. Driven by the user
    /// setting (`SettingsStore.historyRetentionDays`), synced by `AppModel`.
    var retentionDays = 7
    private var lastMetricSample: Date?
    private var lastRetentionPrune: Date?
    private var recentEvents: [String: Date] = [:]
    /// Minimum spacing between persisted metric samples, so a 2s poll doesn't flood the DB
    /// (60s → ~10k rows per container over the 7-day window).
    private let metricInterval: TimeInterval = 60
    /// Suppress identical durable Activity rows generated by repeated background ticks.
    private let duplicateEventWindow: TimeInterval = 30

    init(database: AppDatabase = AppDatabase()) {
        self.database = database
        self.container = database.container
        self.reader = HistoryReader(modelContainer: database.container)
        pruneOld()
        refreshSummary()
    }

    // MARK: Writes

    func record(_ kind: EventKind, containerID: String? = nil, message: String, at date: Date = Date()) {
        guard database.canPersist else { return }
        pruneIfDue(now: date)
        guard database.canPersist else { return }
        let key = [kind.rawValue, containerID ?? "", message].joined(separator: "\u{1F}")
        if let last = recentEvents[key], date.timeIntervalSince(last) < duplicateEventWindow { return }
        let record = EventRecord(timestamp: date, containerID: containerID, kind: kind, message: message)
        context.insert(record)
        guard save() else { return }
        recentEvents[key] = date
        recentEvents = recentEvents.filter { date.timeIntervalSince($0.value) < duplicateEventWindow }
        activitySummary.totalEvents += 1
        activitySummary.unreadEvents += 1
        if recentActivityLoaded {
            recentActivity.insert(ActivityEvent(record), at: 0)
            if recentActivity.count > Self.recentActivityLimit {
                recentActivity.removeLast(recentActivity.count - Self.recentActivityLimit)
            }
        }
        activityRevision &+= 1
    }

    /// Persist a metric sample for each running container, throttled to `metricInterval`.
    func recordMetrics(_ scopedDeltas: [String: Core.Metrics.StatsDelta], at date: Date = Date()) {
        guard database.canPersist else { return }
        pruneIfDue(now: date)
        guard database.canPersist else { return }
        guard !scopedDeltas.isEmpty else { return }
        if let last = lastMetricSample, date.timeIntervalSince(last) < metricInterval { return }
        for (scopedContainerID, d) in scopedDeltas {
            context.insert(MetricSample(timestamp: date, containerID: scopedContainerID,
                                        cpuFraction: d.cpuCoreFraction, memoryBytes: Double(d.memoryUsageBytes),
                                        netRxBytesPerSec: d.netRxBytesPerSec, netTxBytesPerSec: d.netTxBytesPerSec,
                                        diskReadBytesPerSec: d.blockReadBytesPerSec, diskWriteBytesPerSec: d.blockWriteBytesPerSec))
        }
        if save() { lastMetricSample = date }
    }

    /// Mark every recorded event as read (clears the toolbar unread badge).
    func markAllEventsRead() {
        guard database.canPersist else { return }
        let unread: [EventRecord]
        do {
            unread = try context.fetch(FetchDescriptor<EventRecord>(
                predicate: #Predicate { !$0.isRead }))
        } catch {
            database.recordFailure(.fetch(model: "EventRecord", detail: AppDatabase.safeDetail(error)))
            return
        }
        guard !unread.isEmpty else { return }
        for event in unread { event.isRead = true }
        guard save() else { return }
        activitySummary.unreadEvents = 0
        recentActivity = recentActivity.map { event in
            var event = event
            event.isRead = true
            return event
        }
        activityRevision &+= 1
    }

    /// Delete every recorded event (keeps metric samples + templates). Backs the Activity "Clear" action.
    func clearEvents() {
        guard database.canPersist else { return }
        guard delete(EventRecord.self), save() else { return }
        activitySummary.totalEvents = 0
        activitySummary.unreadEvents = 0
        recentActivity.removeAll()
        activityRevision &+= 1
    }

    func loadRecentActivity(force: Bool = false) async {
        guard force || !recentActivityLoaded else { return }
        let interval = PerformanceSignposts.activity.beginInterval("ActivityLoad")
        defer { PerformanceSignposts.activity.endInterval("ActivityLoad", interval) }
        do {
            recentActivity = try await reader.recentEvents(limit: Self.recentActivityLimit)
            recentActivityLoaded = true
            activityRevision &+= 1
        } catch {
            database.recordFailure(.fetch(model: "EventRecord", detail: AppDatabase.safeDetail(error)))
        }
    }

    func setEventRead(_ id: PersistentIdentifier, isRead: Bool) {
        guard database.canPersist else { return }
        guard let record = context.model(for: id) as? EventRecord, record.isRead != isRead else { return }
        record.isRead = isRead
        guard save() else { return }
        activitySummary.unreadEvents = max(0, activitySummary.unreadEvents + (isRead ? -1 : 1))
        if let index = recentActivity.firstIndex(where: { $0.id == id }) {
            recentActivity[index].isRead = isRead
        }
        activityRevision &+= 1
    }

    func markEventsRead(kind: EventKind?) {
        guard database.canPersist else { return }
        let records: [EventRecord]
        if let kind {
            let raw = kind.rawValue
            records = fetch(EventRecord.self, predicate: #Predicate { !$0.isRead && $0.kindRaw == raw })
        } else {
            records = fetch(EventRecord.self, predicate: #Predicate { !$0.isRead })
        }
        guard !records.isEmpty else { return }
        for record in records { record.isRead = true }
        guard save() else { return }
        refreshSummary()
        recentActivity = recentActivity.map { event in
            var event = event
            if kind == nil || event.kind == kind { event.isRead = true }
            return event
        }
        activityRevision &+= 1
    }

    func deleteEvent(_ id: PersistentIdentifier) {
        guard database.canPersist else { return }
        guard let record = context.model(for: id) as? EventRecord else { return }
        context.delete(record)
        guard save() else { return }
        recentActivity.removeAll { $0.id == id }
        refreshSummary()
        activityRevision &+= 1
    }

    func clearEvents(kind: EventKind?) {
        guard database.canPersist else { return }
        do {
            if let kind {
                let raw = kind.rawValue
                try context.delete(model: EventRecord.self, where: #Predicate { $0.kindRaw == raw })
            } else {
                try context.delete(model: EventRecord.self)
            }
        } catch {
            database.recordFailure(.save(detail: AppDatabase.safeDetail(error)))
            return
        }
        guard save() else { return }
        if let kind {
            recentActivity.removeAll { $0.kind == kind }
        } else {
            recentActivity.removeAll()
        }
        refreshSummary()
        activityRevision &+= 1
    }

    func containerHistory(scopedContainerID: String, since cutoff: Date) async -> ContainerHistorySnapshot {
        let interval = PerformanceSignposts.activity.beginInterval("ContainerHistoryLoad")
        defer { PerformanceSignposts.activity.endInterval("ContainerHistoryLoad", interval) }
        do {
            return try await reader.containerHistory(scopedContainerID: scopedContainerID, since: cutoff)
        } catch {
            database.recordFailure(.fetch(model: "Container history", detail: AppDatabase.safeDetail(error)))
            return ContainerHistorySnapshot()
        }
    }

    func containerMetrics(scopedContainerID: String, since cutoff: Date) async -> [MetricSampleSnapshot] {
        do {
            return try await reader.containerMetrics(scopedContainerID: scopedContainerID, since: cutoff)
        } catch {
            database.recordFailure(.fetch(model: "Container metrics", detail: AppDatabase.safeDetail(error)))
            return []
        }
    }

    func containerEvents(scopedContainerID: String, since cutoff: Date) async -> [ActivityEvent] {
        do {
            return try await reader.containerEvents(scopedContainerID: scopedContainerID, since: cutoff)
        } catch {
            database.recordFailure(.fetch(model: "Container events", detail: AppDatabase.safeDetail(error)))
            return []
        }
    }

    // MARK: Retention

    private func pruneIfDue(now: Date) {
        if lastRetentionPrune.map({ now.timeIntervalSince($0) >= 3600 }) ?? true {
            pruneOld(now: now)
        }
    }

    func pruneOld(now: Date = Date()) {
        guard database.canPersist else { return }
        guard let cutoff = Calendar.current.date(byAdding: .day, value: -retentionDays, to: now) else { return }
        do {
            try context.delete(model: MetricSample.self, where: #Predicate { $0.timestamp < cutoff })
            try context.delete(model: EventRecord.self, where: #Predicate { $0.timestamp < cutoff })
        } catch {
            database.recordFailure(.save(detail: AppDatabase.safeDetail(error)))
            return
        }
        if save() {
            lastRetentionPrune = now
            database.maintainTransactionHistory()
            refreshSummary()
            if recentActivityLoaded {
                Task { await loadRecentActivity(force: true) }
            }
        }
    }

    /// Wipe all recorded metrics and events (Templates are preserved). Used by the "Clear history"
    /// action in Settings.
    func clearAll() {
        guard database.canPersist else { return }
        guard delete(MetricSample.self), delete(EventRecord.self), save() else { return }
        recentActivity.removeAll()
        refreshSummary()
        activityRevision &+= 1
    }

    func templatesSnapshot() -> [RecipeSnapshot] {
        fetch(RecipeRecord.self).compactMap(RecipeSnapshot.init)
    }

    func historySnapshot() -> HistoryBackup {
        let events = fetch(EventRecord.self).map(EventRecordSnapshot.init)
        let metrics = fetch(MetricSample.self).map(MetricSampleSnapshot.init)
        return HistoryBackup(events: events, metrics: metrics)
    }

    func applyTemplates(_ snapshots: [RecipeSnapshot], replace: Bool) {
        guard database.canPersist else { return }
        if replace {
            guard delete(RecipeRecord.self) else { return }
        }
        for snapshot in snapshots {
            context.insert(RecipeRecord(snapshot: snapshot))
        }
        guard save() else { return }
        refreshSummary()
    }

    func applyHistory(_ snapshot: HistoryBackup, replace: Bool) {
        guard database.canPersist else { return }
        if replace {
            guard delete(EventRecord.self), delete(MetricSample.self) else { return }
        }
        for event in snapshot.events { context.insert(EventRecord(snapshot: event)) }
        for metric in snapshot.metrics { context.insert(MetricSample(snapshot: metric)) }
        guard save() else { return }
        refreshSummary()
        if recentActivityLoaded { Task { await loadRecentActivity(force: true) } }
    }

    func insertTemplate(_ record: RecipeRecord) {
        guard database.canPersist else { return }
        context.insert(record)
        guard save() else { return }
        activitySummary.templateCount += 1
    }

    func deleteTemplate(_ record: RecipeRecord) {
        guard database.canPersist else { return }
        context.delete(record)
        guard save() else { return }
        activitySummary.templateCount = max(0, activitySummary.templateCount - 1)
    }

    func purgeOrphans(liveContainerIDs: Set<String>,
                      authoritativeRuntimeKinds: Set<Core.Runtime.Kind> = Set(Core.Runtime.supportedDescriptors.map(\.kind))) -> (events: Int, metrics: Int) {
        guard database.canPersist else { return (0, 0) }
        guard let allEvents = try? database.fetchRequired(EventRecord.self),
              let allMetrics = try? database.fetchRequired(MetricSample.self) else { return (0, 0) }
        func isOrphan(_ id: String) -> Bool {
            let scoped = Core.Runtime.Kind.parseScopedID(id)
            let kind = scoped?.kind ?? .appleContainer
            let live = liveContainerIDs.contains(id) || (scoped == nil && liveContainerIDs.contains(kind.scopedID(for: id)))
            return authoritativeRuntimeKinds.contains(kind) && !live
        }
        let events = allEvents
            .filter { $0.containerID.map(isOrphan) ?? false }
        let metrics = allMetrics
            .filter { isOrphan($0.containerID) }
        for event in events { context.delete(event) }
        for metric in metrics { context.delete(metric) }
        guard save() else { return (0, 0) }
        refreshSummary()
        if recentActivityLoaded { Task { await loadRecentActivity(force: true) } }
        return (events.count, metrics.count)
    }

    @discardableResult
    private func save() -> Bool { database.save() }

    private func refreshSummary() {
        _ = reloadFromDatabase(refreshRecent: false)
    }

    /// Refresh all projections together; a failed read must not replace prior values with zeros.
    @discardableResult
    func reloadFromDatabase(refreshRecent: Bool = true) -> Bool {
        do {
            let total = try database.readRequired(EventRecord.self) {
                try context.fetchCount(FetchDescriptor<EventRecord>())
            }
            let unread = try database.readRequired(EventRecord.self) {
                try context.fetchCount(FetchDescriptor<EventRecord>(predicate: #Predicate { !$0.isRead }))
            }
            let templates = try database.readRequired(RecipeRecord.self) {
                try context.fetchCount(FetchDescriptor<RecipeRecord>())
            }
            var events: [ActivityEvent]?
            if refreshRecent, recentActivityLoaded {
                var descriptor = FetchDescriptor<EventRecord>(sortBy: [SortDescriptor(\EventRecord.timestamp, order: .reverse)])
                descriptor.fetchLimit = Self.recentActivityLimit
                events = try database.readRequired(EventRecord.self) { try context.fetch(descriptor).map(ActivityEvent.init) }
            }
            activitySummary = ActivitySummary(totalEvents: total, unreadEvents: unread, templateCount: templates)
            if let events { recentActivity = events }
            activityRevision &+= 1
            return true
        } catch { return false }
    }

    private func fetch<T: PersistentModel>(_ model: T.Type) -> [T] {
        do {
            return try context.fetch(FetchDescriptor<T>())
        } catch {
            database.recordFailure(.fetch(model: String(describing: T.self), detail: AppDatabase.safeDetail(error)))
            return []
        }
    }

    private func fetch<T: PersistentModel>(_ model: T.Type,
                                           predicate: Predicate<T>) -> [T] {
        do {
            return try context.fetch(FetchDescriptor<T>(predicate: predicate))
        } catch {
            database.recordFailure(.fetch(model: String(describing: T.self), detail: AppDatabase.safeDetail(error)))
            return []
        }
    }

    @discardableResult
    private func delete<T: PersistentModel>(_ model: T.Type) -> Bool {
        do {
            try context.delete(model: T.self)
            return true
        } catch {
            database.recordFailure(.save(detail: AppDatabase.safeDetail(error)))
            return false
        }
    }
}

@ModelActor
actor HistoryReader {
    func recentEvents(limit: Int) throws -> [ActivityEvent] {
        var descriptor = FetchDescriptor<EventRecord>(
            sortBy: [SortDescriptor(\EventRecord.timestamp, order: .reverse)]
        )
        descriptor.fetchLimit = limit
        return try modelContext.fetch(descriptor).map(ActivityEvent.init)
    }

    func containerHistory(scopedContainerID: String, since cutoff: Date) throws -> ContainerHistorySnapshot {
        ContainerHistorySnapshot(metrics: try containerMetrics(scopedContainerID: scopedContainerID, since: cutoff),
                                 events: try containerEvents(scopedContainerID: scopedContainerID, since: cutoff))
    }

    func containerMetrics(scopedContainerID: String, since cutoff: Date) throws -> [MetricSampleSnapshot] {
        try modelContext.fetch(FetchDescriptor<MetricSample>(
            predicate: #Predicate { $0.containerID == scopedContainerID && $0.timestamp >= cutoff },
            sortBy: [SortDescriptor(\MetricSample.timestamp)]
        )).map(MetricSampleSnapshot.init)
    }

    func containerEvents(scopedContainerID: String, since cutoff: Date) throws -> [ActivityEvent] {
        var eventDescriptor = FetchDescriptor<EventRecord>(
            predicate: #Predicate { $0.containerID == scopedContainerID && $0.timestamp >= cutoff },
            sortBy: [SortDescriptor(\EventRecord.timestamp, order: .reverse)]
        )
        eventDescriptor.fetchLimit = 50
        return try modelContext.fetch(eventDescriptor).map(ActivityEvent.init)
    }
}

struct HistoryBackup: Codable, Equatable {
    var events: [EventRecordSnapshot]
    var metrics: [MetricSampleSnapshot]
}

enum HistorySchemaV1: VersionedSchema {
    static var versionIdentifier: Schema.Version { Schema.Version(1, 0, 0) }
    static var models: [any PersistentModel.Type] {
        [EventRecord.self, MetricSample.self, RecipeRecord.self]
    }
}

enum HistoryMigrationPlan: SchemaMigrationPlan {
    static var schemas: [any VersionedSchema.Type] { [HistorySchemaV1.self] }
    static var stages: [MigrationStage] { [] }
}
