import Foundation
import SwiftData
import ContainedCore

/// Writes persistent history (events + metric samples) into the shared app database.
/// Retention-bounded so the database can't grow without limit. The `container` is exposed so the
/// SwiftUI views can read it via `@Query`.
@MainActor
final class HistoryStore {
    let container: ModelContainer
    private let database: AppDatabase
    private var context: ModelContext { container.mainContext }

    /// Keep this many days of history; pruned on launch and periodically. Driven by the user
    /// setting (`SettingsStore.historyRetentionDays`), synced by `AppModel`.
    var retentionDays = 7
    private var lastMetricSample: Date?
    private var recentEvents: [String: Date] = [:]
    /// Minimum spacing between persisted metric samples, so a 2s poll doesn't flood the DB
    /// (60s → ~10k rows per container over the 7-day window).
    private let metricInterval: TimeInterval = 60
    /// Suppress identical durable Activity rows generated by repeated background ticks.
    private let duplicateEventWindow: TimeInterval = 30

    init(database: AppDatabase = AppDatabase()) {
        self.database = database
        self.container = database.container
        pruneOld()
    }

    // MARK: Writes

    func record(_ kind: EventKind, containerID: String? = nil, message: String, at date: Date = Date()) {
        let key = [kind.rawValue, containerID ?? "", message].joined(separator: "\u{1F}")
        if let last = recentEvents[key], date.timeIntervalSince(last) < duplicateEventWindow { return }
        recentEvents[key] = date
        recentEvents = recentEvents.filter { date.timeIntervalSince($0.value) < duplicateEventWindow }
        context.insert(EventRecord(timestamp: date, containerID: containerID, kind: kind, message: message))
        save()
    }

    /// Persist a metric sample for each running container, throttled to `metricInterval`.
    func recordMetrics(_ deltas: [String: Core.Metrics.StatsDelta], at date: Date = Date()) {
        if let last = lastMetricSample, date.timeIntervalSince(last) < metricInterval { return }
        lastMetricSample = date
        for (id, d) in deltas {
            context.insert(MetricSample(timestamp: date, containerID: id,
                                        cpuFraction: d.cpuCoreFraction, memoryBytes: Double(d.memoryUsageBytes),
                                        netRxBytesPerSec: d.netRxBytesPerSec, netTxBytesPerSec: d.netTxBytesPerSec,
                                        diskReadBytesPerSec: d.blockReadBytesPerSec, diskWriteBytesPerSec: d.blockWriteBytesPerSec))
        }
        save()
    }

    /// Mark every recorded event as read (clears the toolbar unread badge).
    func markAllEventsRead() {
        let unread: [EventRecord]
        do {
            unread = try context.fetch(FetchDescriptor<EventRecord>(
                predicate: #Predicate { !$0.isRead }))
        } catch {
            database.recordFailure(.fetch(model: "EventRecord", detail: String(describing: error)))
            return
        }
        guard !unread.isEmpty else { return }
        for event in unread { event.isRead = true }
        save()
    }

    /// Delete every recorded event (keeps metric samples + templates). Backs the Activity "Clear" action.
    func clearEvents() {
        delete(EventRecord.self)
        save()
    }

    // MARK: Retention

    func pruneOld(now: Date = Date()) {
        guard let cutoff = Calendar.current.date(byAdding: .day, value: -retentionDays, to: now) else { return }
        do {
            try context.delete(model: MetricSample.self, where: #Predicate { $0.timestamp < cutoff })
            try context.delete(model: EventRecord.self, where: #Predicate { $0.timestamp < cutoff })
        } catch {
            database.recordFailure(.save(detail: "Unable to prune history: \(error)"))
        }
        save()
    }

    /// Wipe all recorded metrics and events (Templates are preserved). Used by the "Clear history"
    /// action in Settings.
    func clearAll() {
        delete(MetricSample.self)
        delete(EventRecord.self)
        save()
    }

    func unreadEventCount() -> Int {
        do {
            return try context.fetchCount(FetchDescriptor<EventRecord>(
                predicate: #Predicate { !$0.isRead }))
        } catch {
            database.recordFailure(.fetch(model: "EventRecord", detail: String(describing: error)))
            return 0
        }
    }

    func templatesSnapshot() -> [RecipeSnapshot] {
        fetch(RecipeRecord.self).compactMap(RecipeSnapshot.init)
    }

    func historySnapshot() -> HistoryBackup {
        let events = fetch(EventRecord.self).map(EventRecordSnapshot.init)
        let metrics = fetch(MetricSample.self).map(MetricSampleSnapshot.init)
        return HistoryBackup(events: events, metrics: metrics)
    }

    func applyTemplates(_ snapshots: [RecipeSnapshot], replace: Bool) {
        if replace {
            delete(RecipeRecord.self)
        }
        for snapshot in snapshots {
            context.insert(RecipeRecord(snapshot: snapshot))
        }
        save()
    }

    func applyHistory(_ snapshot: HistoryBackup, replace: Bool) {
        if replace {
            delete(EventRecord.self)
            delete(MetricSample.self)
        }
        for event in snapshot.events { context.insert(EventRecord(snapshot: event)) }
        for metric in snapshot.metrics { context.insert(MetricSample(snapshot: metric)) }
        save()
    }

    func purgeOrphans(liveContainerIDs: Set<String>) -> (events: Int, metrics: Int) {
        let events = fetch(EventRecord.self)
            .filter { $0.containerID.map { !liveContainerIDs.contains($0) } ?? false }
        let metrics = fetch(MetricSample.self)
            .filter { !liveContainerIDs.contains($0.containerID) }
        for event in events { context.delete(event) }
        for metric in metrics { context.delete(metric) }
        save()
        return (events.count, metrics.count)
    }

    private func save() {
        do {
            try context.save()
        } catch {
            database.recordFailure(.save(detail: "Unable to save history data: \(error)"))
        }
    }

    private func fetch<T: PersistentModel>(_ model: T.Type) -> [T] {
        do {
            return try context.fetch(FetchDescriptor<T>())
        } catch {
            database.recordFailure(.fetch(model: String(describing: T.self), detail: String(describing: error)))
            return []
        }
    }

    private func delete<T: PersistentModel>(_ model: T.Type) {
        do {
            try context.delete(model: T.self)
        } catch {
            database.recordFailure(.save(detail: "Unable to delete \(T.self): \(error)"))
        }
    }
}

struct HistoryBackup: Codable, Equatable {
    var events: [EventRecordSnapshot]
    var metrics: [MetricSampleSnapshot]
}

enum HistorySchemaV1: VersionedSchema {
    static var versionIdentifier: Schema.Version { Schema.Version(1, 0, 0) }
    static var models: [any PersistentModel.Type] {
        [EventRecord.self, MetricSample.self, RecipeRecord.self]
    }
}

enum HistoryMigrationPlan: SchemaMigrationPlan {
    static var schemas: [any VersionedSchema.Type] { [HistorySchemaV1.self] }
    static var stages: [MigrationStage] { [] }
}
